language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
env:
  - TARGET=redmine REDMINE_VERSION=4.0.3
  - TARGET=plugin REDMINE_VERSION=4.0.3
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh
addons:
  chrome: stable
matrix:
  allow_failures:
    - rvm: 2.3
      env: TARGET=redmine REDMINE_VERSION=4.0.3
    - rvm: 2.4
      env: TARGET=redmine REDMINE_VERSION=4.0.3
    - rvm: 2.5
      env: TARGET=redmine REDMINE_VERSION=4.0.3
    - rvm: 2.6
      env: TARGET=redmine REDMINE_VERSION=4.0.3
